import { randomBytes } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { generateRegistrationOptions } from "@simplewebauthn/server";
import { prisma } from "@/lib/prisma";
import { rpName, rpID, setPendingRegistration } from "@/lib/webauthn";

// Starts either of the two ways to create an account:
//  - setupToken: the one-time bootstrap, only valid while zero accounts exist
//  - inviteToken: a link generated by an existing account
// Exactly one must be provided. Neither requires a session — you don't have
// one yet.
export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => null);
  const displayName = typeof body?.displayName === "string" ? body.displayName.trim() : "";
  const setupToken = typeof body?.setupToken === "string" ? body.setupToken : undefined;
  const inviteToken = typeof body?.inviteToken === "string" ? body.inviteToken : undefined;

  if (!displayName || displayName.length > 60) {
    return NextResponse.json({ error: "Enter a name (up to 60 characters)." }, { status: 400 });
  }
  if (!setupToken === !inviteToken) {
    return NextResponse.json({ error: "Invalid signup link." }, { status: 400 });
  }

  if (setupToken) {
    const expected = process.env.SETUP_TOKEN;
    const userCount = await prisma.user.count();
    if (!expected || setupToken !== expected || userCount > 0) {
      return NextResponse.json({ error: "Setup is no longer available." }, { status: 403 });
    }
  } else if (inviteToken) {
    const invite = await prisma.invite.findUnique({ where: { token: inviteToken } });
    if (!invite || invite.usedAt || invite.expiresAt < new Date()) {
      return NextResponse.json({ error: "This invite link is invalid or has expired." }, { status: 404 });
    }
  }

  const userID = randomBytes(32);
  const options = await generateRegistrationOptions({
    rpName,
    rpID: rpID(),
    userName: userID.toString("hex"),
    userDisplayName: displayName,
    userID,
    attestationType: "none",
    authenticatorSelection: {
      residentKey: "required",
      userVerification: "required",
      authenticatorAttachment: "platform",
    },
  });

  await setPendingRegistration({ challenge: options.challenge, displayName, setupToken, inviteToken });

  return NextResponse.json(options);
}
